### ISSUE TITLE
space

### ISSUE THREAD

**Issue by xujinge** [tumarkin/yente#1]
Yente doesn't handle the space well. It matches "Ashoknagar" with "Tikamgarh" instead of "Ashok Nagar". Overall, it works great. Thanks!

**Comment by tumarkin** [comment]
It seems the issue is that you have versions of the name both with spaces and without. Yente in its current form assumes all spaces are placed correctly. That's how it is able to match without a concern for the word order. Have you tried the above match with the misspelling penalty set? That may work. I can also update the program so it will deal with this case. Please give me some time, but let me know if the misspelling penalty works for you.

**Comment by xujinge** [comment]
I did use the misspelling penalty.

yente districts_dise_20190328.csv districts_wiki_20190328.csv -o
districts_dise_wiki_20190328.csv -g --soundex --misspelling-penalty=2

Another problem I found is that when there are two matches that both have
scored 1 (one is an exact match, one has score 1 because of minor
difference), the exact match is not picked. For example,
Shivpuri is matched with Sheopur though the tofile has Shivpuri. I used the
above code.

**Comment by tumarkin** [comment]
Thanks! I understand the issue now. 

I added a ngram-based misspelling feature that will catch these kinds of matching problems. In this case, both names are missing a space - I originally thought it was just one. 

To use this, add the option `--ngram-size=Integer`. You should try `--ngram-size=2` to start. It can not be used at the same time as the original `misspelling-penalty` option, which uses a different algorithm. 

I tried this on a test sample where one file had first name-last name (no space) and the other file was last name-first name (no space). It worked well.

`yente --help` is updated, with the. Github FAQ soon to follow.

Your example command probably doesn't require Soundex anymore. So, I would try:

`yente districts_dise_20190328.csv districts_wiki_20190328.csv -o districts_dise_wiki_20190328.csv -g --ngram-size=2`

Please let me know how it works.

**Comment by xujinge** [comment]
Sorry for the late reply.

I tried the --ngram-size=2. It fixed the problem.

**Comment by xujinge** [comment]
Thanks !
